### ISSUE TITLE
telegramBotToken ISSUE

### ISSUE THREAD

**Issue by BAIOGIT** [dimotsai/pokeradar-notification#2]
hi there, i report my issue ( ....... stands for my alphabetical token)

/index.js:22
    telegramBotToken: ........ ,
                      ^

ReferenceError: ......... is not defined
    at Object.<anonymous> (/Users/aaaaa/Downloads/pokemongo-notification-master/index.js:22:23)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Function.Module.runMain (module.js:441:10)
    at startup (node.js:139:18)
    at node.js:974:3

thank you for reading this

**Comment by dimotsai** [comment]
Quote your bot token.

``` javascript
{
  telegramBotToken: "YOUR_BOT_TOKEN"
}
```

**Comment by BAIOGIT** [comment]
hi than you for answer!

{
  telegramBotToken: "AAG0lSIvMrxROvXFe5HOuR2WEomNrjIPU"
}

2016-09-17 13:28 GMT+02:00 Dimo notifications@github.com:
